# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  success:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run success
        run: exit 0
      - name: Send message to Telegram
        uses: ./
        if: always()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
        with:
          status: ${{job.status}}
  fail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run fail
        run: exit 1
      - name: Send message to Telegram
        uses: ./
        if: always()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
        with:
          status: ${{job.status}}
  no-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run success
        run: exit 0
      - name: Send message to Telegram
        uses: ./
        if: always()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
  alternative-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run success
        run: exit 0
      - name: Send message to Telegram
        uses: ./
        if: always()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
        with:
          commit_template: ./templates/commit-alternative.mustache
          status: ${{job.status}}
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Print env
        run: env

      - name: Print gcc ver
        run: gcc -v

      - name: Build
        run: g++ hello.cpp -o app
      
      - name: Success alert
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TEXT: "✅ <b>Deployed</b>%0A${{ github.event.workflow_run.head_commit.message }} <i>(${{ github.event.workflow_run.head_branch }})</i>"
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TELEGRAM_TO }}
        run: |
          curl -X GET "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage?chat_id=$TELEGRAM_TO&text=$TEXT"

      - name: Failure alert
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TEXT: "🚨🚨🚨 <b>Deployment Failed</b>%0A${{ github.event.workflow_run.head_commit.message }} <i>(${{ github.event.workflow_run.head_branch }})</i>❌"
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TELEGRAM_TO }}
        run: |
          curl -X GET "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage?chat_id=$TELEGRAM_TO&text=$TEXT"
